
Sell:
  items:
    stone: 1
    coal: 1
    sat: 1
    vang: 1
    kc: 1
    nlb: 1
    dado: 1
    thanhanh: 1
    lapis: 1
    wood: 1
    paddy: 1
    cactus: 1
    pumpkin: 1
    watermelon: 1
    sugarcane: 1
    beetroots: 1
    carot: 1
    potato: 1